-- MySQL Script generated by MySQL Workbench
-- Sat Nov 26 19:31:41 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cultivo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `cultivo` ;

-- -----------------------------------------------------
-- Schema cultivo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cultivo` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `cultivo` ;

-- -----------------------------------------------------
-- Table `cultivo`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cultivo`.`users` ;

CREATE TABLE IF NOT EXISTS `cultivo`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `apellido_pat` VARCHAR(45) NULL COMMENT '',
  `apellido_mat` VARCHAR(45) NULL COMMENT '',
  `email` VARCHAR(255) NOT NULL COMMENT '',
  `password` VARCHAR(255) NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  UNIQUE INDEX `username_UNIQUE` (`email` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultivo`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cultivo`.`locations` ;

CREATE TABLE IF NOT EXISTS `cultivo`.`locations` (
  `id` INT NOT NULL COMMENT '',
  `nombre` VARCHAR(45) NOT NULL COMMENT '',
  `latitud` VARCHAR(45) NULL COMMENT '',
  `longitud` VARCHAR(45) NULL COMMENT '',
  `admin_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '',
  PRIMARY KEY (`id`, `admin_id`)  COMMENT '',
  INDEX `fk_locations_users_idx` (`admin_id` ASC)  COMMENT '',
  CONSTRAINT `fk_locations_users`
    FOREIGN KEY (`admin_id`)
    REFERENCES `cultivo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cultivo`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `cultivo`.`visits` ;

CREATE TABLE IF NOT EXISTS `cultivo`.`visits` (
  `id` INT NOT NULL COMMENT '',
  `locations_id` INT NOT NULL COMMENT '',
  `users_id` INT NOT NULL COMMENT '',
  `created_at` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '',
  `updated_at` TIMESTAMP NOT NULL DEFAULT NOW() COMMENT '',
  PRIMARY KEY (`id`, `users_id`)  COMMENT '',
  INDEX `fk_visits_locations1_idx` (`locations_id` ASC)  COMMENT '',
  INDEX `fk_visits_users1_idx` (`users_id` ASC)  COMMENT '',
  CONSTRAINT `fk_visits_locations1`
    FOREIGN KEY (`locations_id`)
    REFERENCES `cultivo`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `cultivo`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

CREATE USER 'cultivo'@'localhost' IDENTIFIED BY 'cultivo';
GRANT ALL PRIVILEGES ON cultivo . * TO 'cultivo'@'localhost';